// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCasz_X3o4UTYxIDs5uqOg3gWRsYCv1ks',
    appId: '1:749016741757:web:d7dff03c8a35d1afae7e14',
    messagingSenderId: '749016741757',
    projectId: 'data-maps-42670',
    authDomain: 'data-maps-42670.firebaseapp.com',
    storageBucket: 'data-maps-42670.appspot.com',
    measurementId: 'G-MP59JKK4TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJlyB2qsQH_cwBjVZkHzaYsk4BwIDPHQs',
    appId: '1:749016741757:android:248efa303d3f4404ae7e14',
    messagingSenderId: '749016741757',
    projectId: 'data-maps-42670',
    storageBucket: 'data-maps-42670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9V6LxyTymYaJrtZv4W_J32eadYntCpNw',
    appId: '1:749016741757:ios:7547fc8f9fb4d668ae7e14',
    messagingSenderId: '749016741757',
    projectId: 'data-maps-42670',
    storageBucket: 'data-maps-42670.appspot.com',
    androidClientId: '749016741757-tkogj1dlucriiojemub52quus7aqj863.apps.googleusercontent.com',
    iosClientId: '749016741757-e3v59vuu94u41m1isrueg413n8hi5ihe.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9V6LxyTymYaJrtZv4W_J32eadYntCpNw',
    appId: '1:749016741757:ios:7547fc8f9fb4d668ae7e14',
    messagingSenderId: '749016741757',
    projectId: 'data-maps-42670',
    storageBucket: 'data-maps-42670.appspot.com',
    androidClientId: '749016741757-tkogj1dlucriiojemub52quus7aqj863.apps.googleusercontent.com',
    iosClientId: '749016741757-e3v59vuu94u41m1isrueg413n8hi5ihe.apps.googleusercontent.com',
    iosBundleId: 'com.example.capstone',
  );
}
